
GET https://us-central1-socialape-6fd1c.cloudfunctions.net/api/screams

###

POST https://us-central1-socialape-6fd1c.cloudfunctions.net/api/login
content-type: application/json

{
    "email": "test3@gmail.com",
    "password": "test3@gmail.com"

}

###

GET https://us-central1-socialape-6fd1c.cloudfunctions.net/api/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ5ZTg4YzUzNzYxOTk2YTczNjIzZjE5MWQ1MTJkMmI0N2RmODAyYTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBlLTZmZDFjIiwiYXVkIjoic29jaWFsYXBlLTZmZDFjIiwiYXV0aF90aW1lIjoxNTk3NzM0NDU4LCJ1c2VyX2lkIjoiTFo0VExMZ1RzUlN6Rm1tNG0yeXBrT3pnSUNFMyIsInN1YiI6IkxaNFRMTGdUc1JTekZtbTRtMnlwa096Z0lDRTMiLCJpYXQiOjE1OTc3MzQ0NTgsImV4cCI6MTU5NzczODA1OCwiZW1haWwiOiJ0ZXN0M0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdDNAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.qJLbVRQ_tsujDIgi75KCcaq8yIENgDOF5ee1nYYoWTEUMHAlNm4g7_ULLF-E1H9gqlyiuafzJdnLvu1BLP8wMWguRi0ln2kyCxDQehjqux3oYKL5tWwpngkXuZAAj_YsdwjbQAv2dUvJNlYb-PxZ6FMHamkmZ4pR--kgtt411WWk4oVs5q9uhJFNeApT0GCTTVewtY8aTntbvqOTOvQm9bWk65nbsCBLRHWRwy5iRsZ6lOqztlQMmk_17OoGB7CePBR-0atSbRc0IWmp1k7BjLeymnIHnfRVwjdKU3sV_wVRK1nVXVDSZ7mYcuq0IydaY0PZ1LhQ9rapbAk0_dXqhA

###
POST https://us-central1-socialape-6fd1c.cloudfunctions.net/api/scream
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ5ZTg4YzUzNzYxOTk2YTczNjIzZjE5MWQ1MTJkMmI0N2RmODAyYTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBlLTZmZDFjIiwiYXVkIjoic29jaWFsYXBlLTZmZDFjIiwiYXV0aF90aW1lIjoxNTk3NzM0NDU4LCJ1c2VyX2lkIjoiTFo0VExMZ1RzUlN6Rm1tNG0yeXBrT3pnSUNFMyIsInN1YiI6IkxaNFRMTGdUc1JTekZtbTRtMnlwa096Z0lDRTMiLCJpYXQiOjE1OTc3MzQ0NTgsImV4cCI6MTU5NzczODA1OCwiZW1haWwiOiJ0ZXN0M0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdDNAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.qJLbVRQ_tsujDIgi75KCcaq8yIENgDOF5ee1nYYoWTEUMHAlNm4g7_ULLF-E1H9gqlyiuafzJdnLvu1BLP8wMWguRi0ln2kyCxDQehjqux3oYKL5tWwpngkXuZAAj_YsdwjbQAv2dUvJNlYb-PxZ6FMHamkmZ4pR--kgtt411WWk4oVs5q9uhJFNeApT0GCTTVewtY8aTntbvqOTOvQm9bWk65nbsCBLRHWRwy5iRsZ6lOqztlQMmk_17OoGB7CePBR-0atSbRc0IWmp1k7BjLeymnIHnfRVwjdKU3sV_wVRK1nVXVDSZ7mYcuq0IydaY0PZ1LhQ9rapbAk0_dXqhA

{
    "body":"hi abcdef"
}
